name = "dev_pkg"
uuid = "6e172099-2da4-46e7-8c3f-eb5f14eb67c6"
repo = "https://github.com/dmetivie/LocalRegistry"
description = "Dev pkgs"

[packages]
3d8e1505-165e-443f-a184-83a230b5a9e5 = { name = "SmoothPeriodicStatsModels", path = "S/SmoothPeriodicStatsModels" }
3eadb0b9-5057-49d2-9b8f-52a8c334ebf6 = { name = "StochasticWeatherGenerators", path = "S/StochasticWeatherGenerators" }
6a06312b-1f35-42d8-b2e0-a51b61531d54 = { name = "ABCMethods", path = "A/ABCMethods" }
cefad46e-21aa-447d-abc5-91039c0799ef = { name = "ConcreteDropoutLayer", path = "C/ConcreteDropoutLayer" }
